### ISSUE TITLE
ImportHEKAtoMat.m not in the file

### ISSUE THREAD

**Issue by PeterBX** [curiousgeorgie/Matlab-PatchMaster#1]
Hi Curousgerogie,
I would like to import PatchMaster files in Matlab and followed the instruction. However, ImportHEKAtoMat.m is not part of the download and therefore I'm not able to replace the ImportHEKA function with ImportHEKAtoMat as stated in your comment. Could you please provide this file as well?
Thanks a lot!
Best,
peter

**Comment by sammykatta** [comment]
Apologies, I only just saw this. I've added a copy of the function to the repo. Let me know if you have any problems using it!

**Comment by PeterBX** [comment]
Thanks so much for your assistance! I will check the files next week and leave a message if I still have problems.
